export interface Country {
  name: string;
  dial_code: string;
  code: string;
  isLive?: boolean;
}

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', dial_code: '', code: 'AF', isLive: false },
  { name: 'Albania', dial_code: '', code: 'AL', isLive: false },
  { name: 'Algeria', dial_code: '', code: 'DZ', isLive: false },
  { name: 'American Samoa', dial_code: '', code: 'AS', isLive: false },
  { name: 'Andorra', dial_code: '', code: 'AD', isLive: false },
  { name: 'Angola', dial_code: '', code: 'AO', isLive: false },
  { name: 'Anguilla', dial_code: '', code: 'AI', isLive: false },
  { name: 'Antarctica', dial_code: '', code: 'AQ', isLive: false },
  { name: 'Antigua and Barbuda', dial_code: '', code: 'AG', isLive: false },
  { name: 'Argentina', dial_code: '', code: 'AR', isLive: false },
  { name: 'Armenia', dial_code: '', code: 'AM', isLive: false },
  { name: 'Aruba', dial_code: '', code: 'AW', isLive: false },
  { name: 'Australia', dial_code: '', code: 'AU', isLive: false },
  { name: 'Austria', dial_code: '', code: 'AT', isLive: false },
  { name: 'Azerbaijan', dial_code: '', code: 'AZ', isLive: false },
  { name: 'Bahamas', dial_code: '', code: 'BS', isLive: false },
  { name: 'Bahrain', dial_code: '', code: 'BH', isLive: true },
  { name: 'Bangladesh', dial_code: '', code: 'BD', isLive: false },
  { name: 'Barbados', dial_code: '', code: 'BB', isLive: false },
  { name: 'Belarus', dial_code: '', code: 'BY', isLive: false },
  { name: 'Belgium', dial_code: '', code: 'BE', isLive: false },
  { name: 'Belize', dial_code: '', code: 'BZ', isLive: false },
  { name: 'Benin', dial_code: '', code: 'BJ', isLive: false },
  { name: 'Bermuda', dial_code: '', code: 'BM', isLive: false },
  { name: 'Bhutan', dial_code: '', code: 'BT', isLive: false },
  { name: 'Bolivia', dial_code: '', code: 'BO', isLive: false },
  { name: 'Bosnia and Herzegovina', dial_code: '', code: 'BA', isLive: false },
  { name: 'Botswana', dial_code: '', code: 'BW', isLive: false },
  { name: 'Bouvet Island', dial_code: '', code: 'BV', isLive: false },
  { name: 'Brazil', dial_code: '', code: 'BR', isLive: false },
  { name: 'British Indian Ocean Territory', dial_code: '', code: 'IO', isLive: false },
  { name: 'Brunei Darussalam', dial_code: '', code: 'BN', isLive: false },
  { name: 'Bulgaria', dial_code: '', code: 'BG', isLive: false },
  { name: 'Burkina Faso', dial_code: '', code: 'BF', isLive: false },
  { name: 'Burundi', dial_code: '', code: 'BI', isLive: false },
  { name: 'Cambodia', dial_code: '', code: 'KH', isLive: false },
  { name: 'Cameroon', dial_code: '', code: 'CM', isLive: false },
  { name: 'Canada', dial_code: '', code: 'CA', isLive: false },
  { name: 'Cape Verde', dial_code: '', code: 'CV', isLive: false },
  { name: 'Cayman Islands', dial_code: '', code: 'KY', isLive: false },
  { name: 'Central African Republic', dial_code: '', code: 'CF', isLive: false },
  { name: 'Chad', dial_code: '', code: 'TD', isLive: false },
  { name: 'Chile', dial_code: '', code: 'CL', isLive: false },
  { name: 'People\'s Republic of China', dial_code: '', code: 'CN', isLive: false },
  { name: 'Christmas Island', dial_code: '', code: 'CX', isLive: false },
  { name: 'Cocos (Keeling) Islands', dial_code: '', code: 'CC', isLive: false },
  { name: 'Colombia', dial_code: '', code: 'CO', isLive: false },
  { name: 'Comoros', dial_code: '', code: 'KM', isLive: false },
  { name: 'Republic of the Congo', dial_code: '', code: 'CG', isLive: false },
  { name: 'Democratic Republic of the Congo', dial_code: '', code: 'CD', isLive: false },
  { name: 'Cook Islands', dial_code: '', code: 'CK', isLive: false },
  { name: 'Costa Rica', dial_code: '', code: 'CR', isLive: false },
  { name: 'Cote d\'Ivoire', dial_code: '', code: 'CI', isLive: false },
  { name: 'Croatia', dial_code: '', code: 'HR', isLive: false },
  { name: 'Cuba', dial_code: '', code: 'CU', isLive: false },
  { name: 'Cyprus', dial_code: '', code: 'CY', isLive: false },
  { name: 'Czech Republic', dial_code: '', code: 'CZ', isLive: false },
  { name: 'Denmark', dial_code: '', code: 'DK', isLive: false },
  { name: 'Djibouti', dial_code: '', code: 'DJ', isLive: false },
  { name: 'Dominica', dial_code: '', code: 'DM', isLive: false },
  { name: 'Dominican Republic', dial_code: '', code: 'DO', isLive: false },
  { name: 'Ecuador', dial_code: '', code: 'EC', isLive: false },
  { name: 'Egypt', dial_code: '', code: 'EG', isLive: false },
  { name: 'El Salvador', dial_code: '', code: 'SV', isLive: false },
  { name: 'Equatorial Guinea', dial_code: '', code: 'GQ', isLive: false },
  { name: 'Eritrea', dial_code: '', code: 'ER', isLive: false },
  { name: 'Estonia', dial_code: '', code: 'EE', isLive: false },
  { name: 'Ethiopia', dial_code: '', code: 'ET', isLive: false },
  { name: 'Falkland Islands (Malvinas)', dial_code: '', code: 'FK', isLive: false },
  { name: 'Faroe Islands', dial_code: '', code: 'FO', isLive: false },
  { name: 'Fiji', dial_code: '', code: 'FJ', isLive: false },
  { name: 'Finland', dial_code: '', code: 'FI', isLive: false },
  { name: 'France', dial_code: '', code: 'FR', isLive: false },
  { name: 'French Guiana', dial_code: '', code: 'GF', isLive: false },
  { name: 'French Polynesia', dial_code: '', code: 'PF', isLive: false },
  { name: 'French Southern Territories', dial_code: '', code: 'TF', isLive: false },
  { name: 'Gabon', dial_code: '', code: 'GA', isLive: false },
  { name: 'Republic of The Gambia', dial_code: '', code: 'GM', isLive: false },
  { name: 'Georgia', dial_code: '', code: 'GE', isLive: false },
  { name: 'Germany', dial_code: '', code: 'DE', isLive: false },
  { name: 'Ghana', dial_code: '', code: 'GH', isLive: false },
  { name: 'Gibraltar', dial_code: '', code: 'GI', isLive: false },
  { name: 'Greece', dial_code: '', code: 'GR', isLive: false },
  { name: 'Greenland', dial_code: '', code: 'GL', isLive: false },
  { name: 'Grenada', dial_code: '', code: 'GD', isLive: false },
  { name: 'Guadeloupe', dial_code: '', code: 'GP', isLive: false },
  { name: 'Guam', dial_code: '', code: 'GU', isLive: false },
  { name: 'Guatemala', dial_code: '', code: 'GT', isLive: false },
  { name: 'Guinea', dial_code: '', code: 'GN', isLive: false },
  { name: 'Guinea-Bissau', dial_code: '', code: 'GW', isLive: false },
  { name: 'Guyana', dial_code: '', code: 'GY', isLive: false },
  { name: 'Haiti', dial_code: '', code: 'HT', isLive: false },
  { name: 'Heard Island and McDonald Islands', dial_code: '', code: 'HM', isLive: false },
  { name: 'Holy See (Vatican City State)', dial_code: '', code: 'VA', isLive: false },
  { name: 'Honduras', dial_code: '', code: 'HN', isLive: false },
  { name: 'Hong Kong', dial_code: '', code: 'HK', isLive: false },
  { name: 'Hungary', dial_code: '', code: 'HU', isLive: false },
  { name: 'Iceland', dial_code: '', code: 'IS', isLive: false },
  { name: 'India', dial_code: '', code: 'IN', isLive: false },
  { name: 'Indonesia', dial_code: '', code: 'ID', isLive: false },
  { name: 'Islamic Republic of Iran', dial_code: '', code: 'IR', isLive: false },
  { name: 'Iraq', dial_code: '', code: 'IQ', isLive: false },
  { name: 'Ireland', dial_code: '', code: 'IE', isLive: false },
  { name: 'Israel', dial_code: '', code: 'IL', isLive: false },
  { name: 'Italy', dial_code: '', code: 'IT', isLive: false },
  { name: 'Jamaica', dial_code: '', code: 'JM', isLive: false },
  { name: 'Japan', dial_code: '', code: 'JP', isLive: false },
  { name: 'Jordan', dial_code: '', code: 'JO', isLive: false },
  { name: 'Kazakhstan', dial_code: '', code: 'KZ', isLive: false },
  { name: 'Kenya', dial_code: '', code: 'KE', isLive: false },
  { name: 'Kiribati', dial_code: '', code: 'KI', isLive: false },
  { name: 'North Korea', dial_code: '', code: 'KP', isLive: false },
  { name: 'South Korea', dial_code: '', code: 'KR', isLive: false },
  { name: 'Kuwait', dial_code: '', code: 'KW', isLive: true },
  { name: 'Kyrgyzstan', dial_code: '', code: 'KG', isLive: false },
  { name: 'Lao People\'s Democratic Republic', dial_code: '', code: 'LA', isLive: false },
  { name: 'Latvia', dial_code: '', code: 'LV', isLive: false },
  { name: 'Lebanon', dial_code: '', code: 'LB', isLive: false },
  { name: 'Lesotho', dial_code: '', code: 'LS', isLive: false },
  { name: 'Liberia', dial_code: '', code: 'LR', isLive: false },
  { name: 'Libya', dial_code: '', code: 'LY', isLive: false },
  { name: 'Liechtenstein', dial_code: '', code: 'LI', isLive: false },
  { name: 'Lithuania', dial_code: '', code: 'LT', isLive: false },
  { name: 'Luxembourg', dial_code: '', code: 'LU', isLive: false },
  { name: 'Macao', dial_code: '', code: 'MO', isLive: false },
  { name: 'Madagascar', dial_code: '', code: 'MG', isLive: false },
  { name: 'Malawi', dial_code: '', code: 'MW', isLive: false },
  { name: 'Malaysia', dial_code: '', code: 'MY', isLive: false },
  { name: 'Maldives', dial_code: '', code: 'MV', isLive: false },
  { name: 'Mali', dial_code: '', code: 'ML', isLive: false },
  { name: 'Malta', dial_code: '', code: 'MT', isLive: false },
  { name: 'Marshall Islands', dial_code: '', code: 'MH', isLive: false },
  { name: 'Martinique', dial_code: '', code: 'MQ', isLive: false },
  { name: 'Mauritania', dial_code: '', code: 'MR', isLive: false },
  { name: 'Mauritius', dial_code: '', code: 'MU', isLive: false },
  { name: 'Mayotte', dial_code: '', code: 'YT', isLive: false },
  { name: 'Mexico', dial_code: '', code: 'MX', isLive: false },
  { name: 'Micronesia, Federated States of', dial_code: '', code: 'FM', isLive: false },
  { name: 'Moldova, Republic of', dial_code: '', code: 'MD', isLive: false },
  { name: 'Monaco', dial_code: '', code: 'MC', isLive: false },
  { name: 'Mongolia', dial_code: '', code: 'MN', isLive: false },
  { name: 'Montserrat', dial_code: '', code: 'MS', isLive: false },
  { name: 'Morocco', dial_code: '', code: 'MA', isLive: false },
  { name: 'Mozambique', dial_code: '', code: 'MZ', isLive: false },
  { name: 'Myanmar', dial_code: '', code: 'MM', isLive: false },
  { name: 'Namibia', dial_code: '', code: 'NA', isLive: false },
  { name: 'Nauru', dial_code: '', code: 'NR', isLive: false },
  { name: 'Nepal', dial_code: '', code: 'NP', isLive: false },
  { name: 'Netherlands', dial_code: '', code: 'NL', isLive: false },
  { name: 'New Caledonia', dial_code: '', code: 'NC', isLive: false },
  { name: 'New Zealand', dial_code: '', code: 'NZ', isLive: false },
  { name: 'Nicaragua', dial_code: '', code: 'NI', isLive: false },
  { name: 'Niger', dial_code: '', code: 'NE', isLive: false },
  { name: 'Nigeria', dial_code: '', code: 'NG', isLive: false },
  { name: 'Niue', dial_code: '', code: 'NU', isLive: false },
  { name: 'Norfolk Island', dial_code: '', code: 'NF', isLive: false },
  { name: 'The Republic of North Macedonia', dial_code: '', code: 'MK', isLive: false },
  { name: 'Northern Mariana Islands', dial_code: '', code: 'MP', isLive: false },
  { name: 'Norway', dial_code: '', code: 'NO', isLive: false },
  { name: 'Oman', dial_code: '', code: 'OM', isLive: true },
  { name: 'Pakistan', dial_code: '', code: 'PK', isLive: false },
  { name: 'Palau', dial_code: '', code: 'PW', isLive: false },
  { name: 'State of Palestine', dial_code: '', code: 'PS', isLive: false },
  { name: 'Panama', dial_code: '', code: 'PA', isLive: false },
  { name: 'Papua New Guinea', dial_code: '', code: 'PG', isLive: false },
  { name: 'Paraguay', dial_code: '', code: 'PY', isLive: false },
  { name: 'Peru', dial_code: '', code: 'PE', isLive: false },
  { name: 'Philippines', dial_code: '', code: 'PH', isLive: false },
  { name: 'Pitcairn', dial_code: '', code: 'PN', isLive: false },
  { name: 'Poland', dial_code: '', code: 'PL', isLive: false },
  { name: 'Portugal', dial_code: '', code: 'PT', isLive: false },
  { name: 'Puerto Rico', dial_code: '', code: 'PR', isLive: false },
  { name: 'Qatar', dial_code: '', code: 'QA', isLive: true },
  { name: 'Reunion', dial_code: '', code: 'RE', isLive: false },
  { name: 'Romania', dial_code: '', code: 'RO', isLive: false },
  { name: 'Russian Federation', dial_code: '', code: 'RU', isLive: false },
  { name: 'Rwanda', dial_code: '', code: 'RW', isLive: false },
  { name: 'Saint Helena', dial_code: '', code: 'SH', isLive: false },
  { name: 'Saint Kitts and Nevis', dial_code: '', code: 'KN', isLive: false },
  { name: 'Saint Lucia', dial_code: '', code: 'LC', isLive: false },
  { name: 'Saint Pierre and Miquelon', dial_code: '', code: 'PM', isLive: false },
  { name: 'Saint Vincent and the Grenadines', dial_code: '', code: 'VC', isLive: false },
  { name: 'Samoa', dial_code: '', code: 'WS', isLive: false },
  { name: 'San Marino', dial_code: '', code: 'SM', isLive: false },
  { name: 'Sao Tome and Principe', dial_code: '', code: 'ST', isLive: false },
  { name: 'Saudi Arabia', dial_code: '', code: 'SA', isLive: true },
  { name: 'Senegal', dial_code: '', code: 'SN', isLive: false },
  { name: 'Seychelles', dial_code: '', code: 'SC', isLive: false },
  { name: 'Sierra Leone', dial_code: '', code: 'SL', isLive: false },
  { name: 'Singapore', dial_code: '', code: 'SG', isLive: false },
  { name: 'Slovakia', dial_code: '', code: 'SK', isLive: false },
  { name: 'Slovenia', dial_code: '', code: 'SI', isLive: false },
  { name: 'Solomon Islands', dial_code: '', code: 'SB', isLive: false },
  { name: 'Somalia', dial_code: '', code: 'SO', isLive: false },
  { name: 'South Africa', dial_code: '', code: 'ZA', isLive: false },
  { name: 'South Georgia and the South Sandwich Islands', dial_code: '', code: 'GS', isLive: false },
  { name: 'Spain', dial_code: '', code: 'ES', isLive: false },
  { name: 'Sri Lanka', dial_code: '', code: 'LK', isLive: false },
  { name: 'Sudan', dial_code: '', code: 'SD', isLive: false },
  { name: 'Suriname', dial_code: '', code: 'SR', isLive: false },
  { name: 'Svalbard and Jan Mayen', dial_code: '', code: 'SJ', isLive: false },
  { name: 'Eswatini', dial_code: '', code: 'SZ', isLive: false },
  { name: 'Sweden', dial_code: '', code: 'SE', isLive: false },
  { name: 'Switzerland', dial_code: '', code: 'CH', isLive: false },
  { name: 'Syrian Arab Republic', dial_code: '', code: 'SY', isLive: false },
  { name: 'Taiwan, Province of China', dial_code: '', code: 'TW', isLive: false },
  { name: 'Tajikistan', dial_code: '', code: 'TJ', isLive: false },
  { name: 'United Republic of Tanzania', dial_code: '', code: 'TZ', isLive: false },
  { name: 'Thailand', dial_code: '', code: 'TH', isLive: false },
  { name: 'Timor-Leste', dial_code: '', code: 'TL', isLive: false },
  { name: 'Togo', dial_code: '', code: 'TG', isLive: false },
  { name: 'Tokelau', dial_code: '', code: 'TK', isLive: false },
  { name: 'Tonga', dial_code: '', code: 'TO', isLive: false },
  { name: 'Trinidad and Tobago', dial_code: '', code: 'TT', isLive: false },
  { name: 'Tunisia', dial_code: '', code: 'TN', isLive: false },
  { name: 'Türkiye', dial_code: '', code: 'TR', isLive: false },
  { name: 'Turkmenistan', dial_code: '', code: 'TM', isLive: false },
  { name: 'Turks and Caicos Islands', dial_code: '', code: 'TC', isLive: false },
  { name: 'Tuvalu', dial_code: '', code: 'TV', isLive: false },
  { name: 'Uganda', dial_code: '', code: 'UG', isLive: false },
  { name: 'Ukraine', dial_code: '', code: 'UA', isLive: false },
  { name: 'United Arab Emirates', dial_code: '', code: 'AE', isLive: true },
  { name: 'United Kingdom', dial_code: '', code: 'GB', isLive: false },
  { name: 'United States of America', dial_code: '', code: 'US', isLive: false },
  { name: 'United States Minor Outlying Islands', dial_code: '', code: 'UM', isLive: false },
  { name: 'Uruguay', dial_code: '', code: 'UY', isLive: false },
  { name: 'Uzbekistan', dial_code: '', code: 'UZ', isLive: false },
  { name: 'Vanuatu', dial_code: '', code: 'VU', isLive: false },
  { name: 'Venezuela', dial_code: '', code: 'VE', isLive: false },
  { name: 'Vietnam', dial_code: '', code: 'VN', isLive: false },
  { name: 'Virgin Islands, British', dial_code: '', code: 'VG', isLive: false },
  { name: 'Virgin Islands, U.S.', dial_code: '', code: 'VI', isLive: false },
  { name: 'Wallis and Futuna', dial_code: '', code: 'WF', isLive: false },
  { name: 'Western Sahara', dial_code: '', code: 'EH', isLive: false },
  { name: 'Yemen', dial_code: '', code: 'YE', isLive: false },
  { name: 'Zambia', dial_code: '', code: 'ZM', isLive: false },
  { name: 'Zimbabwe', dial_code: '', code: 'ZW', isLive: false },
  { name: 'Åland Islands', dial_code: '', code: 'AX', isLive: false },
  { name: 'Bonaire, Sint Eustatius and Saba', dial_code: '', code: 'BQ', isLive: false },
  { name: 'Curaçao', dial_code: '', code: 'CW', isLive: false },
  { name: 'Guernsey', dial_code: '', code: 'GG', isLive: false },
  { name: 'Isle of Man', dial_code: '', code: 'IM', isLive: false },
  { name: 'Jersey', dial_code: '', code: 'JE', isLive: false },
  { name: 'Montenegro', dial_code: '', code: 'ME', isLive: false },
  { name: 'Saint Barthélemy', dial_code: '', code: 'BL', isLive: false },
  { name: 'Saint Martin (French part)', dial_code: '', code: 'MF', isLive: false },
  { name: 'Serbia', dial_code: '', code: 'RS', isLive: false },
  { name: 'Sint Maarten (Dutch part)', dial_code: '', code: 'SX', isLive: false },
  { name: 'South Sudan', dial_code: '', code: 'SS', isLive: false },
  { name: 'Kosovo', dial_code: '', code: 'XK', isLive: false },
];

export const POPULAR_COUNTRIES: string[] = ['AE', 'SA', 'QA', 'KW', 'OM', 'BH'];
